# Конфигурация LangServe сервера для анализа изображений еды

# Настройки сервера
server:
  host: "0.0.0.0"
  port: 8000
  log_level: "info"
  title: "Food Image Analyzer API"
  description: "API для анализа изображений еды с помощью LangChain и OpenAI"
  version: "1.0.0"

# Настройки OpenAI
openai:
  model: "gpt-4o"
  temperature: 0.5
  max_tokens: 1000
  timeout: 60

# Настройки Edamam Food Database API
edamam:
  app_id: "e6a6f9f9"
  app_key: "9e39a6bc205b6e1639628a107b0629c9"
  base_url: "https://api.edamam.com/api/food-database/v2/parser"
  timeout: 30
  max_results: 10