# Конфигурация веб-приложения Food Tracker

# Настройки сервера
server:
  host: "0.0.0.0"
  port: 5001
  debug: true

# Настройки базы данных
database:
  url: "sqlite:///app.db"
  track_modifications: false

# Настройки загрузки файлов
upload:
  folder: "uploads"
  max_content_length_mb: 16
  allowed_extensions: ["png", "jpg", "jpeg", "gif", "webp"]

# Настройки безопасности
security:
  remember_cookie_duration_days: 7
  secret_key: null  # Будет автоматически сгенерирован

# Настройки почты
mail:
  server: "smtp.example.com"
  port: 465
  username: "username"
  password: "password"
  default_sender: "noreply@example.com"
  use_tls: true
  use_ssl: true

# Настройки интеграции с chain-server
chain_server:
  url: "http://localhost:8000"
  analyze_endpoint: "/analyze"
  timeout: 30