# Пример конфигурации веб-приложения Food Tracker
# Скопируйте этот файл в config.yaml и настройте под свои нужды

# Настройки сервера
server:
  host: "0.0.0.0"          # Адрес для прослушивания
  port: 5001               # Порт сервера
  debug: true              # Режим отладки (false для продакшена)

# Настройки базы данных
database:
  url: "sqlite:///app.db"  # URL базы данных
  track_modifications: false

# Настройки загрузки файлов
upload:
  folder: "uploads"        # Папка для загруженных файлов
  max_content_length_mb: 16  # Максимальный размер файла в MB
  allowed_extensions: ["png", "jpg", "jpeg", "gif", "webp"]

# Настройки безопасности
security:
  remember_cookie_duration_days: 7  # Время жизни cookie "запомнить меня"
  secret_key: null         # Секретный ключ (null = автогенерация)

# Настройки почты
mail:
  server: "smtp.gmail.com"     # SMTP сервер (Gmail)
  port: 587                    # Порт SMTP (587 для TLS, 465 для SSL)
  username: "your-email@gmail.com"  # Ваш email
  password: "your-app-password"     # Пароль приложения (не основной пароль!)
  default_sender: "noreply@foodtracker.com"  # Отправитель по умолчанию
  use_tls: true               # Использовать TLS (Gmail: true)
  use_ssl: false              # Использовать SSL (Gmail: false)

# Настройки интеграции с chain-server
chain_server:
  url: "http://localhost:8000"     # URL chain-сервера
  analyze_endpoint: "/analyze"     # Endpoint для анализа изображения
  analyze_full_endpoint: "/analyze-full"  # Комбинированный endpoint (изображение→блюда→нутриенты)
  timeout: 30                      # Таймаут запроса в секундах

# Функциональные флаги
features:
  single_request_mode: false       # При true используется единый запрос и одна кнопка